
(require 'el-repos)
(require 'el-appearance)
(require 'el-start-screen)
(require 'el-search-packages)
(require 'el-tree)
(require 'el-window)
(require 'el-helm)
(require 'el-google)
(require 'el-yasnippet)
(require 'el-pocket)
(require 'el-reddit)
(require 'el-shell)

(provide 'el-base-setings)
